### PR TITLE
[Fixes] and [Updates]

### PR DESCRIPTION
**Pull request by abhijithvijayan**
- Installed docsify-cli via npm [globally](https://docsifyjs.github.io/docsify-cli/#/?id=installation)
as `./node_modules/docsify-cli/bin/docsify serve docs` won't run in Windows
- Updated Docs

### CODE REVIEW

**Comment by abhijithvijayan** [comment]
Fixes #278

**Comment by markypython** [comment]
@abhijithvijayan Requiring that the package is installed globally is not as easy as using the executable in the `node_modules` folder.  Can you explain why you believe it is better to have it installed globally?

**Comment by abhijithvijayan** [comment]
> 
> 
> @abhijithvijayan Requiring that the package is installed globally is not as easy as using the executable in the `node_modules` folder. Can you explain why you believe it is better to have it installed globally?

In windows cmd/Cmder won't recognize scripts starting with ```./node_modules/docsify-cli/bin/``` 
So the best way to launch the livereload server is by installing `docsify-cli` globally according to the official [docs](https://docsifyjs.github.io/docsify-cli/#/?id=installation)

**Comment by markypython** [comment]
@abhijithvijayan Ah, I see.  In that case, the best way to handle this would be to add a script to `package.json`, i.e. ` "docs": "docsify serve docs"` and then call it by running `npm run docs`.

**Comment by abhijithvijayan** [comment]
> "docs": "docsify serve docs"

That is not a bad idea. Let me make the changes for that.

**Pull request merged**
