### PR TITLE
feat: set the foreground color for the property name in CSS Preprocessor

### PR DESCRIPTION
**Pull request by liby**
Specific changes:
1. Solved #285
2. By the way, add space between English and Chinese in the i18n file

<details>
<summary>Compare</summary>

demo-less-before
demo-less-after
demo-css-in-js-before
demo-css-in-js-after

</details>

### CODE REVIEW

**Comment by Binaryify** [comment]
It should not preset a color, but let the user define it

**Comment by liby** [comment]
> It should not preset a color, but let the user define it

The preset values are mainly due to the following reasons:
1. It is reasonable to believe that there are still some users who do not know where to define it, and capable users know where to override the preset values. 
    - For customers who don't have such a need, it doesn't make any difference to them whether they set the color or not.
2. Using the OneDark-Pro theme with other plugins will override the settings of the other plugins, resulting in no syntax highlighting in the CSS property name section. e.g.: [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components)
    - It will cause unnecessary misunderstanding, leading users to think that there are problems with the plug-in and so on, the declaration of preset values in the theme can be a good way to prevent this.
 3. Syntax highlighting is one strategy to improve the readability and context of the text, and the CSS property name deserves to be highlighted, too.

The above is my personal opinion, as to whether to use depends on your choice.

**Comment by Binaryify** [comment]
If you have seen the issues of this project in the past, you will see that when you change a setting that many people are used to, some people will support you, and the other half will oppose you, so let the user customize it, not set the default value
like https://github.com/Binaryify/OneDark-Pro/issues/565 
https://github.com/Binaryify/OneDark-Pro/issues/529
https://github.com/Binaryify/OneDark-Pro/issues/394

**Comment by liby** [comment]
> when you change a setting that many people are used to

- First of all, the CSS property name is not quite the same as the ones you mentioned, so it is not appropriate to discuss them together.

> so let the user customize it, not set the default value

- Secondly, I think it would be more appropriate to compare it with the CSS attribute name, Constants, Class name, etc. Why is it possible to set syntax highlighting for them? Won't this affect the user's habits?

> like #565
> #529
> #394

- Finally, these examples you gave are either UI settings for the editor or variables, they are distinctly different from the CSS property name that is clearly defined in the syntax. So why can't you give syntax highlighting to something that is clearly syntactically well defined?

**Comment by Binaryify** [comment]
you didn't get my point, I mean if one change will make more than 20% users feel bad, you should let user custom by themself, color perception is very subjective, and I don't think it's necessary to set CSS property names to other colors, too much color can interfere with attention

**Comment by liby** [comment]
>  I mean if one change will make more than 20% users feel bad, you should let user custom by themself,

Can you tell me how the `20%` figure was obtained?

> and I don't think it's necessary to set CSS property names to other colors, too much color can interfere with attention

So you haven't answered me why "Keywords, Constants, and Class name can be highlighted, won't they distract the user's attention? How did you determine that setting them up made `100%` of users happy?

**Comment by Binaryify** [comment]
20% is based on my previous experience， "Keywords, Constants, and Class name can be highlighted" is because people needs to know the variable type，but CSS property names is not necessary, people know it's CSS property names

**Comment by Binaryify** [comment]
based on my previous experience, after I merge this PR and release a new version, 100% will have user ask me to change it back

**Pull request closed without merging**
