### PR TITLE
Gnome/adwaita theme for one dark

### PR DESCRIPTION
**Pull request by MalcolmMielle**
A theme that fits within gnome/adwaita and a very dark+bright green retro theme.

### CODE REVIEW

**Comment by Binaryify** [comment]
thank for the PR, these themes style are different, I suggest delete package.json entry, let user choose those theme in setting menu, also could you merge 2 PR to 1 PR to avoid the conflict?

**Comment by MalcolmMielle** [comment]
Sure. I'm off at the moment I'll come back to it next month!

**Comment by Binaryify** [comment]
> Sure. I'm off at the moment I'll come back to it next month!

okay, have a good time~

**Comment by MalcolmMielle** [comment]
This PR now includes both the retro and gnome theme.

I'm also removed the package.json entry and added them as option in the settings. That says the change seems to be inconsistent :S. It works good when I manually change in the settings.json, but when I trigger it in the UI setting menu, the theme is not always applied. However, I cannot see why I would have this behavior :S.

Could you maybe confirm (or not) if you see the same behavior ?

**Comment by Binaryify** [comment]
@MalcolmMielle the themes in the setting menu, need reload the window to apply, because they are created dynamically

**Comment by Binaryify** [comment]
I will check that~

**Comment by Binaryify** [comment]
Setting only support default theme

**Comment by jaitra1264** [comment]
I am a newbie, how do I enable the retro theme?? it looks so cool

**Comment by Binaryify** [comment]
@jaitra1264 check the vscode setting

**Comment by jaitra1264** [comment]
> @jaitra1264 check the vscode setting

Where and what do I check?

**Comment by jaitra1264** [comment]
do I have to download the retro theme separately or does it come with the one dark theme extension?

**Comment by small-fork** [comment]
Hello @MalcolmMielle I'm brand new to VSCode. I installed "One Dark Pro" but want to use the Gnome option. However, in my VSCode settings, all I'm seeing are these options:
image

There is no Gnome or Retro. Please forgive me if I’m missing something obvious! I'm also very disoriented by GitHub, so I'm likely not understanding how to get the Gnome option to appear. Thank you!

**Comment by MalcolmMielle** [comment]
Hi! If I remember correctly, you have to use the classic one dark pro and the option for retro/gnome is in the settings of the extension. I give it to you that's pretty confusing

**Comment by small-fork** [comment]
@MalcolmMielle Thank you for the reply. I'm not sure if I did this right...I set Workbench to "One Dark Pro" then went into Extensions > One Dark Pro and found Gnome in the "editor" appearance. Before that, the Editor theme dropdown was in the main Appearance settings.

The whole setup is pretty confusing! I don't know if this was right? I'm still not clear on Workbench vs Editor anyways :)

**Pull request merged**
