### PR TITLE
support `global` in node.js

### LINKED ISSUE #103: missing `support.variable.object.node.js`
```
if (!global.XMLHttpRequest) { // make rxjs ajax work in node
    global.XMLHttpRequest = require('xhr2'); // eslint-disable-line global-require
}
```

image

### PR DESCRIPTION
**Pull request by jens1o**
fixes #103

### CODE REVIEW

**Comment by jens1o** [comment]
This was only implemented for typescript, not for javascript.

**Comment by jens1o** [comment]
When will you publish the new version?

**Comment by Binaryify** [comment]
Tomorrow

**Comment by Binaryify** [comment]
Should I add js/jsx support ?

**Comment by jens1o** [comment]
Okay, thanks :)

Well, that would be a huge improvement, but will offer more things to implement... But yes.

**Comment by Binaryify** [comment]
You can use  `support.variable.object.node` instead of  `support.variable.object.node.js`

**Comment by jens1o** [comment]
Wow, that would clean up it, thanks!

**Comment by Binaryify** [comment]
But I'm no sure if it will effect other code

**Comment by jens1o** [comment]
Oh, I see the problem.

**Pull request merged**
