### PR TITLE
Improve colors for Editor Tabs fixes #176

### LINKED ISSUE #176: Editor tabs
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_20.md#more-themable-colors-for-editor-tabs

I suggest to update it after 1.20 version. Thank you!

### PR DESCRIPTION
**Pull request by svipben**
I don't know if colors are good, but they looked pretty well for me.

### CODE REVIEW

**Comment by svipben** [comment]
Forgot to update Vivid theme also. I will close this PR and open another one with the proper branch name.

**Comment by Binaryify** [comment]
it's look good

**Comment by Binaryify** [comment]
I will deal it, don't worry

**Comment by svipben** [comment]
@Binaryify oh okay sorry for that 😄

**Comment by Binaryify** [comment]
maybe will update, because this issue
https://github.com/Binaryify/OneDark-Pro/issues/178

**Comment by svipben** [comment]
@Binaryify I can fix that #178 and also update Vivid to have tab hover coloring too, what do you think?

**Comment by Binaryify** [comment]
yes, that will be better

**Pull request closed without merging**
