### PR TITLE
[MAINT] Move data to JSON format, refactor, organize

### PR DESCRIPTION
**Pull request by scottmwyant**
## Summary
- [x] Move textColors, editorThemes, and tokenColors all into a JSON file.
- [x] Refactor to remove complexity and clarify intent
- [x] Compress code that was unnecessarily spread across different modules
- [x] Pull out dead code and code that was commented out.

### Detail
(first commit of PR at top, most recent at bottom)

- 9a003e9501480516220808fa420a99e6b8fda318 - Just after I moved editorTheme data from individual files into editor.ts, I realized that was misguided and moved them into JSON.

- 4926af677ef28032f8d9d41830d5bbc6becd75ed - Let's change how we use the `generateTheme` function.  Rather than a function that accepts a config object, make `generateTheme` an object that provides two methods.  One method to generate the default theme and another to generate the theme based on the user's settings.  Then clean up everyplace where we're calling the `generateTheme` function.  Also, this will return a `Theme` object, built from a proper constructor.  Before it was an object literal.

- a108cdb4a1544bf9631e626a20fbc23caccee85d - Now the `createEditorTokens` is just reading the JSON file, so that can be pulled into the Theme.ts since the `Theme` constructor is the only place it will be used.

- 8d5e60f716b109948e40eb265b7f69b3a46902a0 - Time to move the color palette data into the JSON file.

- 286696178b8d7240849280f7dcd8af39f4dd3b1c - Now  move the tokenColor data into the JSON file.  This is a big one.  There was a ton of data stored in constants in `syntax.ts`.

- 153371bb2d87c916215c5c94e5587b1b8af2b64a - Now that we have all the data in a nice neat JSON file, we can refactor syntax.ts a bit.

- ee8f6b7cfa4da2c0398f0cd26115c7454c8c7883 - Now let's define an interface for the `tokenColor` objects before we go any further.

-  474814de15b8a2afbc1bd1fdcc11b3ddda149d1d - Now we can finish refactoring syntax.ts and uniqBy.ts.  I felt the `uniqBy` method was particularly complex.  I think it's because it was so abstract.  In the end it's pretty clever what where doing here but now that we have defined the shape of the data we have coming into the function, we can call on the `name` and `scope` properties directly.

-  184c11f9ebdfb33a9690e1bf85df8c0f6ccbb1c2 - Move the refactored `uniqBy` method into `syntax.ts`, since that's the only place it is used.

-   e10e6c639301914564feff8f9df75492d935fe46 - Move the `configFactory` from syntax.ts into Theme.ts since the `Theme` constructor is the only place it is used.

- 42ae4eb6bb74d52869d0211b5bc4be0b5b52f1a5 - Get rid of the `detect-changes` utility since it's only used in one place and it's basically a one-liner.

- 77c535ec999b44ac9fea3233da3134e4a052ac21 - The `updateTheme` method has a bunch of commented out code, so it's  really just deferring to `regenerateTheme`.  Let's clean that up.

- 0c813c993365561a640ccb1d6abf801b9cd36665 - Node's `writeFile` function doesn't return a promise so you used to have to wrap it up in one.  Now you can use the version of the function that does return a promise.

- 8f8dda5ed25f2c063abd04611a018882810d5772 - Instead of detailing the filenames different times, put them in an array and walk the array.

- dbcfd8b5bf12f4b352b1893a65cc8ec671ee9532 - Delete more commented out code and functions that are never called.

- 94820773b88a99f650efa5e1b0a28940fa56b20d - Clean up imports & exports a little.  The convention for the project seems to be to use named exports.

## Testing

I tested this by compiling and launching the extension, I was able to change the editorTheme and use the setBold & setItalic commands.

### Future work
Going through this I see a couple opportunities:

-  I'd suggest changing up the commands so each one toggles the state between true false (bold, italic, and vivid settings).

- Instead of prompting for reload on every config change, only do that when necessary.  It's not necessary to reload the window when toggling bold/italic/vivid.

### CODE REVIEW

**Comment by scottmwyant** [comment]
Hello @Binaryify!  Not sure what you have in mind for the future of this project.  I've been looking at the code a bit and could offer to help maintain things here and there.

**Comment by Binaryify** [comment]
I think the theme config should in single file, that might better

**Comment by scottmwyant** [comment]
Agreed with your last comment.  Actually by the time you made it, I had already created the JSON file.  I apologize for throwing all this on 1 PR.  I should have broken it up a bit.  I at least took the time to detail everything out so you can see where I'm coming from.  I should have just put my comments into the commit messages, but I didn't feel like going back and doing that lol.

Let me know what you think.

**Comment by Binaryify** [comment]
it's ok, you made a good job~

**Comment by Binaryify** [comment]
there have some problem about `generator.ts`
when you import 'vscode' in generator.ts, you can't run `yarn compile`
vscode module only can run in extensions

**Pull request merged**
