### PR TITLE
Make Classes, Functions, Keywords bold

### PR DESCRIPTION
**Pull request by ifahrentholz**
Based on the great "Quiet Light" theme where I like most that important parts of the code are bold I've moved exactly that behavior to OneDark-Pro-bold. I really hope that you're able to merge that :)

P.S. Thanks for your great work on OneDark-Pro!

### CODE REVIEW

**Comment by jens1o** [comment]
@Binaryify could we integrate this better with our script?

**Comment by Binaryify** [comment]
will merge in this weekend

**Comment by Binaryify** [comment]
thank for your PR

**Comment by Jmotionsnow** [comment]
could you possibly make bold support.constant.property-value.css? also change the color of support.type.property-name to a #ddd or # d3d3d3 ... and use a different highlighter for the pseudo-elements entity.other.attribute-name.pseudo-element.

I would be happy with that x'D

**Comment by ifahrentholz** [comment]
@Binaryify I've updated the code quiet a bit to be able to generate independent theme files. The goal was to be able to customize color settings AND also be able to overwrite tokens per theme. 
All themes still can be generated and you can now add theme independent settings in syntax.js which will overwrite the defaults.

**Comment by Binaryify** [comment]
😃

**Comment by Binaryify** [comment]
I just publish new version

**Pull request merged**
