### PR TITLE
Fix border in dropdown appearing without focus

### PR DESCRIPTION
**Pull request by beastdestroyer**
This is related to #269 and an issue that occured where dropdowns got a focus border for no reason. This fixes that change.

@Binaryify

### CODE REVIEW

**Comment by Binaryify** [comment]
you should fix the conflict first

**Comment by beastdestroyer** [comment]
What conflicts, sorry if I'm not getting exactly what you mean

**Comment by beastdestroyer** [comment]
Oops I didn't see it pointed out in my diffs and probably missed the GitLens extension pointing it out, I'll see if I can get it fixed by today

**Comment by beastdestroyer** [comment]
@Binaryify Looks good now, I see no more conflicts on my end

**Pull request merged**
