### PR TITLE
[READY] More Improvements!

### PR DESCRIPTION
**Pull request by beastdestroyer**
Changes:
- Made units red again
- Adjusted colours of operators (+ compound operators) to be consistent, such as `++`, `--` and `*=` etc.
- Improve Punctuation (some)
- Improve some syntax highlighting for languages:
  - Clojure (globals, symbols and constants)
  - CSS/SCSS/LESS (Colour Operators such as * / + -)
  - CoffeeScript (Brung some colours closer to JavaScript, for consistency)
  - Markdown (Lists, better brackets) 
Also, I didn't get through many languages (THAT WELL), VSCode's vanilla languages don't have much to customize, and some of the languages already have pretty good highlighting :)
More info available in the fork's README

## Mini To-Do List
- [x] Explore improving other languages (without their respective extensions)
  - [x] CSS
  - [x] Clojure
  - [x] CoffeeScript
  - [x] Go
  - [x] Groovy
  - [x] HLSL
  - [x] Ini
  - [x] LESS
  - [x] Makefile  
  - [x] Markdown
  - [x] R
  - [x] SCSS
  - [x] SQL
  - [x] Swift
  - [x] Visual Basic
- [x] Revert colour of sidebar to lighter variant

## Final Steps:
- [x] Checking no highlighting is broken across vanilla languages
- [x] Final Review
- [x] Ping to be ready!

### CODE REVIEW

**Comment by beastdestroyer** [comment]
Also fixes #244

**Comment by beastdestroyer** [comment]
@Binaryify @jens1o

**Comment by beastdestroyer** [comment]
Note: Even id you do approve of merging, I don't want to just yet, I just want to polish the Settings GUI also, specifically the new "Add Pattern" control for `files.exclude`, because the hover and active colours just aren't visible, I also want to continue working on more languages too, and fix up a few bugs, let you know when ready!

**Comment by beastdestroyer** [comment]
Mini To-Do List
- [ ] Explore improving other languages (without their respective extensions)
- [ ] Improve colouring of Settings GUI
- [ ] Revert colour of sidebar to lighter variant

**Comment by jens1o** [comment]
ping us if you are ready :)

Thanks for your contribution!

**Comment by beastdestroyer** [comment]
@jens1o Just a question too, since I've bloated the files (~ +5KB like lol), I was wondering if it was possible to have it minified before release to reduce bloatware as much as possible. I wish to explore rewriting (refactoring) the files as a pull request to reduce clutter and make it easier for maintenance too :)

**Comment by beastdestroyer** [comment]
I can confirm that it is ready. Definitely would like you guys to do a quick run over, I still probably missed something, but that should be highly unlikely, ready to merge! @Binaryify @jens1o

**Comment by Binaryify** [comment]
wow, checking now

**Comment by beastdestroyer** [comment]
DAMN thx ~

**Pull request merged**
