### PR TITLE
Adjust the focus for GUIs to be light instead of dark

### PR DESCRIPTION
**Pull request by beastdestroyer**
This change is nothing special and should only increment the patch of 2.17.4 -> 2.17.5

This update changes the focus from `#21252b` (dark border) to `#F8FAFD` (light border) for items such as dropdown and text borders to imrpove accessiblity. Users should always be able to know where the focus is and shouldn't have to look closely to see it. A Light border on a dark background is easily distinguishable.

This SHOULDN'T affect tab borders, word/bracket match borders.

@Binaryify

### CODE REVIEW

**Comment by xiaoyongdong** [comment]
don't like this..

**Comment by Binaryify** [comment]
@xiaoyongdong 
I just make it no too light

**Comment by beastdestroyer** [comment]
Ouch oops, but yh the second change looks better, sorry about that, muddled up the colours

@xiaoyongdong Your first screenshot doesn't show focus, and the swcond one does have focus so there's a border

**Comment by xiaoyongdong** [comment]
@Binaryify sorry, First screenshot doesn't show a border if no foucs because i changed dropdown.border same as dropdown.background.  screenshot 1 is what i expected.  Only hope have a focus border on it like screenshot 2.

**Comment by beastdestroyer** [comment]
Well the focus in screenshot 2 is there to know where the focus is, so when you click on the dropdown and then again to close it, it still borders as that's where the focus is. If you click off it, focus moves. Users should be able to know where they're focusing as much as possible, especially if you use keyboard shortcut and navigation frequently.

It also doesn't look disturbing but ofc that is up to you whether you like it or not, we shouldn't make changes if only a few people out of the possibly thousands that use it

**Comment by xiaoyongdong** [comment]
I think you don't understand what i said.
I mean, currently if no focus on dropdown or remove focus from it, it still had a focus border. like the following:
image

This is just a small suggestion. thx.

**Pull request merged**
