### PR TITLE
fix typo OR fix wrong cast

### PR DESCRIPTION
**Pull request by jens1o**
fixes this: 
image

### CODE REVIEW

**Comment by Binaryify** [comment]
You should solve the conflicts

**Comment by jens1o** [comment]
I was sure there weren't any once I had submitted the pr... Will fix this asap.

**Comment by Binaryify** [comment]
image

**Comment by jens1o** [comment]
Yes, I know that now there are some conflicts.... However....

**Comment by Binaryify** [comment]
@jens1o 
You can use delete your local repo and git clone again

**Comment by jens1o** [comment]
@Binaryify Like this? Can you push an update to the extension? That would be great!

**Comment by Binaryify** [comment]
wait for minutes

**Comment by Binaryify** [comment]
@jens1o 
Done

**Pull request merged**
